language: csharp
solution: PhoneNumberFormatter.sln

matrix:
  include:
    - dotnet: 1.0.1
      mono: none
      dist: trusty
      mono: latest

script:
  - dotnet restore
  - dotnet build PhoneNumberFormatter
  - dotnet test TestCases